import type { ScenarioDefinition } from '../types/aircraft';
import { createAircraft } from './aircraft';
import { createWeatherZone, DEFAULT_WEATHER_ZONES, DEFAULT_RESTRICTED_ZONES } from '../weather/weatherZones';

export const SCENARIOS: Record<string, ScenarioDefinition> = {
  // Phase 2: Scenario 1 - Safe Flight
  scenario_safe: {
    id: 'scenario_safe',
    name: 'Scenario 1: Safe Flight',
    tagline: 'Standard Airway Separation (Safe)',
    description:
      'Three commercial aircraft maintaining standard lateral and vertical separation along parallel navigation corridors with zero conflict risk.',
    aircraft: [
      createAircraft({
        id: 'AC001',
        callsign: 'SKY 101',
        model: 'B787-9',
        x: 150,
        y: 200,
        altitude: 33000,
        speed: 500,
        heading: 90, // Eastbound on Airway J48
        origin: 'JFK',
        destination: 'LHR',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC002',
        callsign: 'AAL 452',
        model: 'A350-900',
        x: 150,
        y: 400,
        altitude: 33000,
        speed: 500,
        heading: 90, // Eastbound on Airway Q102 (200px lateral separation)
        origin: 'MIA',
        destination: 'ORD',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC003',
        callsign: 'DLH 789',
        model: 'B737-MAX8',
        x: 850,
        y: 600,
        altitude: 35000,
        speed: 480,
        heading: 270, // Westbound on Airway J70
        origin: 'FRA',
        destination: 'YYZ',
        status: 'NORMAL',
      }),
    ],
    weatherZones: [],
    restrictedZones: [],
  },

  // Phase 2: Scenario 2 - Predicted Conflict
  scenario_conflict: {
    id: 'scenario_conflict',
    name: 'Scenario 2: Predicted Conflict',
    tagline: 'Converging 90° Intercept at Same Altitude',
    description:
      'Two aircraft on crossing trajectories at FL300 (30,000 ft). As they approach their future intersection, risk escalates from SAFE → WARNING → HIGH_RISK → CRITICAL.',
    aircraft: [
      createAircraft({
        id: 'AC001',
        callsign: 'SKY 101',
        model: 'B777-300ER',
        x: 100,
        y: 360,
        altitude: 30000,
        speed: 520,
        heading: 90, // Eastbound towards (450, 360)
        origin: 'LAX',
        destination: 'JFK',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC002',
        callsign: 'UAL 452',
        model: 'A330-300',
        x: 450,
        y: 710,
        altitude: 30000,
        speed: 520,
        heading: 0, // Northbound towards (450, 360)
        origin: 'DFW',
        destination: 'BOS',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC003',
        callsign: 'BAW 214',
        model: 'A380-800',
        x: 750,
        y: 160,
        altitude: 38000,
        speed: 490,
        heading: 260, // Clear safe corridor
        origin: 'LHR',
        destination: 'SFO',
        status: 'NORMAL',
      }),
    ],
    weatherZones: [],
    restrictedZones: [],
  },

  // Phase 2: Scenario 3 - Altitude Separation
  scenario_altitude: {
    id: 'scenario_altitude',
    name: 'Scenario 3: Altitude Separation',
    tagline: 'Crossing 2D Trajectories with 6,000 ft Vertical Clearance',
    description:
      'Two aircraft have intersecting 2D ground tracks at the center of the sector, but maintain 6,000 ft vertical separation (FL300 vs FL360), resulting in zero collision risk.',
    aircraft: [
      createAircraft({
        id: 'AC001',
        callsign: 'SKY 101',
        model: 'B787-9',
        x: 150,
        y: 375,
        altitude: 30000, // FL300
        speed: 520,
        heading: 90,
        origin: 'BOS',
        destination: 'SFO',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC002',
        callsign: 'AFR 012',
        model: 'A350-900',
        x: 500,
        y: 700,
        altitude: 36000, // FL360 (6,000 ft vertical clearance)
        speed: 520,
        heading: 0,
        origin: 'CDG',
        destination: 'IAH',
        status: 'NORMAL',
      }),
    ],
    weatherZones: [],
    restrictedZones: [],
  },

  // Phase 2: Scenario 4 - Multiple Aircraft Traffic
  scenario_multi: {
    id: 'scenario_multi',
    name: 'Scenario 4: Multiple Aircraft',
    tagline: 'Multi-Traffic Sector with Single Conflict Pair',
    description:
      'Five aircraft operating in the sector. Only SKY 101 and UAL 452 create a predicted conflict, while the other three aircraft fly safely without false positive alerts.',
    aircraft: [
      createAircraft({
        id: 'AC001',
        callsign: 'SKY 101',
        model: 'B737-800',
        x: 120,
        y: 375,
        altitude: 32000,
        speed: 500,
        heading: 90, // Converging with UAL 452
        origin: 'SEA',
        destination: 'DEN',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC002',
        callsign: 'UAL 452',
        model: 'A321neo',
        x: 480,
        y: 720,
        altitude: 32000,
        speed: 500,
        heading: 0, // Converging with SKY 101
        origin: 'DFW',
        destination: 'BOS',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC003',
        callsign: 'QFA 008',
        model: 'B787-9',
        x: 820,
        y: 180,
        altitude: 38000,
        speed: 520,
        heading: 270, // Safe high-altitude corridor
        origin: 'SYD',
        destination: 'JFK',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC004',
        callsign: 'SWA 1940',
        model: 'B737-700',
        x: 180,
        y: 650,
        altitude: 26000,
        speed: 460,
        heading: 30, // Safe lower altitude
        origin: 'PHX',
        destination: 'MDW',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC005',
        callsign: 'KLM 641',
        model: 'B777-200ER',
        x: 820,
        y: 580,
        altitude: 36000,
        speed: 510,
        heading: 270, // Safe westbound corridor
        origin: 'AMS',
        destination: 'ATL',
        status: 'NORMAL',
      }),
    ],
    weatherZones: [],
    restrictedZones: [],
  },

  // Phase 2: Scenario 5 - Head-On Approach
  scenario_headon: {
    id: 'scenario_headon',
    name: 'Scenario 5: Head-On Approach',
    tagline: 'High-Closing-Speed Opposite Headings (180°)',
    description:
      'Two aircraft (AAL 100 and DAL 200) cruising toward each other on the exact same airway (heading 090° vs 270°) at FL320 with over 1,000 kts relative closing speed.',
    aircraft: [
      createAircraft({
        id: 'AC001',
        callsign: 'AAL 100',
        model: 'B777-300ER',
        x: 120,
        y: 375,
        altitude: 32000,
        speed: 540,
        heading: 90, // Eastbound
        origin: 'SFO',
        destination: 'JFK',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC002',
        callsign: 'DAL 200',
        model: 'A350-900',
        x: 880,
        y: 375,
        altitude: 32000,
        speed: 540,
        heading: 270, // Westbound (direct reciprocal heading)
        origin: 'JFK',
        destination: 'SFO',
        status: 'NORMAL',
      }),
    ],
    weatherZones: [],
    restrictedZones: [],
  },

  // ==========================================
  // Phase 3: Weather Scenarios
  // ==========================================

  // Phase 3: Scenario W1 - Clear Airspace
  scenario_weather_clear: {
    id: 'scenario_weather_clear',
    name: 'Weather 1: Clear Airspace',
    tagline: 'Nominal Atmosphere & Standard Airway Routing',
    description:
      'Nominal atmospheric conditions across the sector with zero convective hazards. All aircraft operate safely in standard corridor buffers.',
    aircraft: [
      createAircraft({
        id: 'AC001',
        callsign: 'SKY 101',
        model: 'B787-9',
        x: 150,
        y: 250,
        altitude: 34000,
        speed: 490,
        heading: 90,
        origin: 'ORD',
        destination: 'LGA',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC002',
        callsign: 'DAL 452',
        model: 'A321neo',
        x: 850,
        y: 480,
        altitude: 36000,
        speed: 510,
        heading: 270,
        origin: 'BOS',
        destination: 'DEN',
        status: 'NORMAL',
      }),
    ],
    weatherZones: [],
    restrictedZones: [],
  },

  // Phase 3: Scenario W2 - Storm Ahead
  scenario_weather_storm_ahead: {
    id: 'scenario_weather_storm_ahead',
    name: 'Weather 2: Storm Ahead',
    tagline: 'Direct Convective Storm Cell Intercept',
    description:
      'SKY 101 cruising eastbound at FL320 directly towards an active severe supercell (Storm Cell Alpha). Weather alert triggers with real-time time to entry countdown.',
    aircraft: [
      createAircraft({
        id: 'AC001',
        callsign: 'SKY 101',
        model: 'B777-300ER',
        x: 150,
        y: 375,
        altitude: 32000,
        speed: 500,
        heading: 90, // Flying directly into storm at (550, 375)
        origin: 'SFO',
        destination: 'JFK',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC002',
        callsign: 'SWA 880',
        model: 'B737-800',
        x: 150,
        y: 650,
        altitude: 36000,
        speed: 470,
        heading: 90, // Flying safely below storm on clear southern airway
        origin: 'LAX',
        destination: 'MCO',
        status: 'NORMAL',
      }),
    ],
    weatherZones: [
      createWeatherZone({
        id: 'WZ_STORM_ALPHA',
        name: 'Supercell Storm Alpha',
        type: 'THUNDERSTORM',
        severity: 'CRITICAL',
        center: { x: 550, y: 375 },
        radius: 105,
        windSpeed: 85,
        windHeading: 270,
        visibility: 1.0,
        minAltitudeFt: 0,
        maxAltitudeFt: 45000,
        isActive: true,
        description: 'Severe convective supercell with extreme turbulence and lightning',
      }),
    ],
    restrictedZones: [],
  },

  // Phase 3: Scenario W3 - Aircraft Conflict + Storm
  scenario_weather_conflict_storm: {
    id: 'scenario_weather_conflict_storm',
    name: 'Weather 3: Conflict + Storm',
    tagline: 'Dual Hazard: STCA Converging Traffic + Weather Blockade',
    description:
      'SKY 101 & UAL 452 are in an impending collision conflict. The standard right turn escape vector is blocked by a severe thunderstorm cell, highlighting multi-hazard risk.',
    aircraft: [
      createAircraft({
        id: 'AC001',
        callsign: 'SKY 101',
        model: 'B787-9',
        x: 120,
        y: 360,
        altitude: 31000,
        speed: 520,
        heading: 90, // Eastbound converging on (450, 360)
        origin: 'SEA',
        destination: 'BOS',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC002',
        callsign: 'UAL 452',
        model: 'A330-300',
        x: 450,
        y: 690,
        altitude: 31000,
        speed: 520,
        heading: 0, // Northbound converging on (450, 360)
        origin: 'DFW',
        destination: 'ORD',
        status: 'NORMAL',
      }),
    ],
    weatherZones: [
      createWeatherZone({
        id: 'WZ_ESCAPE_BLOCK',
        name: 'Storm Front Echo',
        type: 'THUNDERSTORM',
        severity: 'HIGH',
        center: { x: 450, y: 220 }, // Blocks northbound escape for UAL452 / northeast turn for SKY101
        radius: 85,
        windSpeed: 70,
        windHeading: 210,
        visibility: 1.5,
        minAltitudeFt: 0,
        maxAltitudeFt: 40000,
        isActive: true,
        description: 'Convective storm cell obstructing standard northern clearance corridors',
      }),
    ],
    restrictedZones: [
      {
        id: 'RZ_MOA_NORTH',
        name: 'Restricted Airspace R-2508',
        center: { x: 250, y: 180 },
        radius: 65,
        minAltitudeFt: 0,
        maxAltitudeFt: 60000,
        status: 'RESTRICTED',
        description: 'Military operating area',
      },
    ],
  },

  // Phase 3: Scenario W4 - Multiple Weather Zones
  scenario_weather_multi: {
    id: 'scenario_weather_multi',
    name: 'Weather 4: Multi-Hazard Sector',
    tagline: 'Thunderstorm, Heavy Rain & Low Visibility Weather Matrix',
    description:
      'Three distinct weather hazard cells operating simultaneously. Multiple aircraft experience distinct weather risks depending on their altitude and trajectory.',
    aircraft: [
      createAircraft({
        id: 'AC001',
        callsign: 'SKY 101',
        model: 'B777-300ER',
        x: 120,
        y: 350,
        altitude: 32000,
        speed: 500,
        heading: 90, // Intersects Storm Alpha
        origin: 'SFO',
        destination: 'JFK',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC002',
        callsign: 'AFR 012',
        model: 'A350-900',
        x: 100,
        y: 560,
        altitude: 20000,
        speed: 460,
        heading: 90, // Intersects Heavy Rain Bravo (at 20,000 ft)
        origin: 'CDG',
        destination: 'MIA',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC003',
        callsign: 'BAW 214',
        model: 'A380-800',
        x: 880,
        y: 220,
        altitude: 38000,
        speed: 520,
        heading: 270, // Overflies Fog Charlie safely (FL380 >> 8000ft ceiling)
        origin: 'LHR',
        destination: 'LAX',
        status: 'NORMAL',
      }),
      createAircraft({
        id: 'AC004',
        callsign: 'DLH 789',
        model: 'B787-9',
        x: 850,
        y: 680,
        altitude: 34000,
        speed: 490,
        heading: 270, // Clear corridor south
        origin: 'FRA',
        destination: 'IAH',
        status: 'NORMAL',
      }),
    ],
    weatherZones: [...DEFAULT_WEATHER_ZONES],
    restrictedZones: [...DEFAULT_RESTRICTED_ZONES],
  },

  // Phase 5: Scenario 1 - Dense Multi-Sector Airspace Fleet (10 Aircraft)
  scenario_phase5_dense_airspace: {
    id: 'scenario_phase5_dense_airspace',
    name: 'Phase 5: High-Density Airspace Fleet',
    tagline: '10 Commercial Aircraft Across 6 ATC Sectors with Waypoint Routes',
    description:
      'Realistic high-density airspace operations with 10 commercial aircraft operating simultaneously across 6 ATC sectors, following multi-waypoint navigation corridors with live traffic density monitoring.',
    aircraft: [
      createAircraft({
        id: 'AC001',
        callsign: 'SKY 101',
        model: 'B787-9',
        x: 80,
        y: 180,
        altitude: 35000,
        speed: 490,
        heading: 85,
        origin: 'JFK',
        destination: 'LHR',
        status: 'NORMAL',
        route: [
          { id: 'WP_ALB', name: 'ALB', x: 280, y: 190, altitude: 35000 },
          { id: 'WP_GDM', name: 'GDM', x: 550, y: 170, altitude: 35000 },
          { id: 'WP_ACK', name: 'ACK', x: 880, y: 160, altitude: 35000 },
        ],
      }),
      createAircraft({
        id: 'AC002',
        callsign: 'AAL 452',
        model: 'A321neo',
        x: 100,
        y: 360,
        altitude: 31000,
        speed: 460,
        heading: 88,
        origin: 'ORD',
        destination: 'BOS',
        status: 'NORMAL',
        route: [
          { id: 'WP_CLE', name: 'CLE', x: 340, y: 360, altitude: 31000 },
          { id: 'WP_JHW', name: 'JHW', x: 620, y: 350, altitude: 31000 },
          { id: 'WP_BOS', name: 'BOS', x: 920, y: 340, altitude: 31000 },
        ],
      }),
      createAircraft({
        id: 'AC003',
        callsign: 'DLH 789',
        model: 'A350-900',
        x: 920,
        y: 220,
        altitude: 37000,
        speed: 510,
        heading: 265,
        origin: 'FRA',
        destination: 'ORD',
        status: 'NORMAL',
        route: [
          { id: 'WP_PUT', name: 'PUT', x: 660, y: 230, altitude: 37000 },
          { id: 'WP_CTR', name: 'CTR', x: 380, y: 240, altitude: 37000 },
          { id: 'WP_SYR', name: 'SYR', x: 100, y: 250, altitude: 37000 },
        ],
      }),
      createAircraft({
        id: 'AC004',
        callsign: 'BAW 214',
        model: 'B777-200',
        x: 880,
        y: 460,
        altitude: 33000,
        speed: 480,
        heading: 272,
        origin: 'LHR',
        destination: 'DFW',
        status: 'NORMAL',
        route: [
          { id: 'WP_IGN', name: 'IGN', x: 600, y: 450, altitude: 33000 },
          { id: 'WP_HNK', name: 'HNK', x: 320, y: 460, altitude: 33000 },
          { id: 'WP_BUF', name: 'BUF', x: 80, y: 470, altitude: 33000 },
        ],
      }),
      createAircraft({
        id: 'AC005',
        callsign: 'UAL 602',
        model: 'B737-MAX9',
        x: 420,
        y: 740,
        altitude: 29000,
        speed: 440,
        heading: 358,
        origin: 'ATL',
        destination: 'BOS',
        status: 'NORMAL',
        route: [
          { id: 'WP_SIE', name: 'SIE', x: 420, y: 520, altitude: 29000 },
          { id: 'WP_BDL', name: 'BDL', x: 440, y: 280, altitude: 29000 },
          { id: 'WP_MHT', name: 'MHT', x: 450, y: 80, altitude: 29000 },
        ],
      }),
      createAircraft({
        id: 'AC006',
        callsign: 'AFR 315',
        model: 'A330-300',
        x: 580,
        y: 740,
        altitude: 36000,
        speed: 495,
        heading: 5,
        origin: 'MIA',
        destination: 'CDG',
        status: 'NORMAL',
        route: [
          { id: 'WP_RIC', name: 'RIC', x: 575, y: 500, altitude: 36000 },
          { id: 'WP_JFK', name: 'JFK', x: 570, y: 260, altitude: 36000 },
          { id: 'WP_PWM', name: 'PWM', x: 565, y: 70, altitude: 36000 },
        ],
      }),
      createAircraft({
        id: 'AC007',
        callsign: 'QFA 011',
        model: 'B787-9',
        x: 120,
        y: 650,
        altitude: 39000,
        speed: 530,
        heading: 55,
        origin: 'SYD',
        destination: 'JFK',
        status: 'NORMAL',
        route: [
          { id: 'WP_MEM', name: 'MEM', x: 380, y: 480, altitude: 39000 },
          { id: 'WP_BNA', name: 'BNA', x: 640, y: 310, altitude: 39000 },
          { id: 'WP_DCA', name: 'DCA', x: 880, y: 150, altitude: 39000 },
        ],
      }),
      createAircraft({
        id: 'AC008',
        callsign: 'SIA 408',
        model: 'A380-800',
        x: 900,
        y: 680,
        altitude: 40000,
        speed: 520,
        heading: 312,
        origin: 'SIN',
        destination: 'YYZ',
        status: 'NORMAL',
        route: [
          { id: 'WP_ILG', name: 'ILG', x: 680, y: 500, altitude: 40000 },
          { id: 'WP_MIP', name: 'MIP', x: 440, y: 330, altitude: 40000 },
          { id: 'WP_ROC', name: 'ROC', x: 180, y: 150, altitude: 40000 },
        ],
      }),
      createAircraft({
        id: 'AC009',
        callsign: 'JAL 005',
        model: 'B777-300ER',
        x: 240,
        y: 70,
        altitude: 34000,
        speed: 475,
        heading: 138,
        origin: 'HND',
        destination: 'JFK',
        status: 'NORMAL',
        route: [
          { id: 'WP_MSS', name: 'MSS', x: 420, y: 230, altitude: 34000 },
          { id: 'WP_BTV', name: 'BTV', x: 620, y: 410, altitude: 34000 },
          { id: 'WP_DXR', name: 'DXR', x: 820, y: 590, altitude: 34000 },
        ],
      }),
      createAircraft({
        id: 'AC010',
        callsign: 'UAE 202',
        model: 'A380-800',
        x: 760,
        y: 80,
        altitude: 38000,
        speed: 515,
        heading: 222,
        origin: 'DXB',
        destination: 'IAD',
        status: 'NORMAL',
        route: [
          { id: 'WP_BGR', name: 'BGR', x: 560, y: 250, altitude: 38000 },
          { id: 'WP_CON', name: 'CON', x: 360, y: 430, altitude: 38000 },
          { id: 'WP_PSM', name: 'PSM', x: 160, y: 610, altitude: 38000 },
        ],
      }),
    ],
    weatherZones: [
      createWeatherZone({
        id: 'WZ_CENTRAL_STORM',
        name: 'Appalachian Storm Cell',
        type: 'THUNDERSTORM',
        severity: 'CRITICAL',
        center: { x: 500, y: 400 },
        radius: 95,
        windSpeed: 68,
        windHeading: 220,
        visibility: 1.0,
        minAltitudeFt: 0,
        maxAltitudeFt: 42000,
        isActive: true,
        description: 'Severe convective thunderstorm cell in central sector',
      }),
    ],
    restrictedZones: [
      {
        id: 'RZ_MOA_NORTH',
        name: 'Restricted Airspace R-2508',
        center: { x: 240, y: 220 },
        radius: 65,
        minAltitudeFt: 0,
        maxAltitudeFt: 60000,
        status: 'RESTRICTED',
        description: 'Military operations area with active live-fire ceiling',
      },
    ],
  },

  // Phase 5: Scenario 2 - Waypoint Route Corridors (8 Aircraft)
  scenario_phase5_waypoint_corridors: {
    id: 'scenario_phase5_waypoint_corridors',
    name: 'Phase 5: Waypoint Airway Corridors',
    tagline: '8 Commercial Aircraft with Multi-Leg Oceanic & Continental Navigation',
    description:
      'Eight aircraft following sequenced waypoint navigation paths across regional corridors with realistic turn rate dynamics and automated waypoint sequencing.',
    aircraft: [
      createAircraft({
        id: 'AC101',
        callsign: 'SKY 201',
        model: 'A350-900',
        x: 80,
        y: 200,
        altitude: 34000,
        speed: 480,
        heading: 90,
        origin: 'SFO',
        destination: 'BOS',
        status: 'NORMAL',
        route: [
          { id: 'WP_A1', name: 'DELTA', x: 300, y: 200, altitude: 34000 },
          { id: 'WP_A2', name: 'ECHO', x: 550, y: 280, altitude: 34000 },
          { id: 'WP_A3', name: 'FOXTROT', x: 850, y: 200, altitude: 34000 },
        ],
      }),
      createAircraft({
        id: 'AC102',
        callsign: 'AAL 712',
        model: 'B777-300',
        x: 880,
        y: 200,
        altitude: 36000,
        speed: 490,
        heading: 270,
        origin: 'LHR',
        destination: 'LAX',
        status: 'NORMAL',
        route: [
          { id: 'WP_B1', name: 'FOXTROT', x: 650, y: 200, altitude: 36000 },
          { id: 'WP_B2', name: 'GOLF', x: 450, y: 150, altitude: 36000 },
          { id: 'WP_B3', name: 'HOTEL', x: 120, y: 200, altitude: 36000 },
        ],
      }),
      createAircraft({
        id: 'AC103',
        callsign: 'DLH 440',
        model: 'B747-8',
        x: 100,
        y: 500,
        altitude: 32000,
        speed: 470,
        heading: 85,
        origin: 'FRA',
        destination: 'MIA',
        status: 'NORMAL',
        route: [
          { id: 'WP_C1', name: 'INDIA', x: 350, y: 490, altitude: 32000 },
          { id: 'WP_C2', name: 'JULIET', x: 600, y: 550, altitude: 32000 },
          { id: 'WP_C3', name: 'KILO', x: 880, y: 520, altitude: 32000 },
        ],
      }),
      createAircraft({
        id: 'AC104',
        callsign: 'UAL 891',
        model: 'B787-10',
        x: 880,
        y: 540,
        altitude: 38000,
        speed: 510,
        heading: 268,
        origin: 'DXB',
        destination: 'IAH',
        status: 'NORMAL',
        route: [
          { id: 'WP_D1', name: 'LIMA', x: 620, y: 530, altitude: 38000 },
          { id: 'WP_D2', name: 'MIKE', x: 380, y: 470, altitude: 38000 },
          { id: 'WP_D3', name: 'NOVEMBER', x: 100, y: 530, altitude: 38000 },
        ],
      }),
      createAircraft({
        id: 'AC105',
        callsign: 'BAW 178',
        model: 'A380-800',
        x: 350,
        y: 750,
        altitude: 30000,
        speed: 450,
        heading: 5,
        origin: 'MCO',
        destination: 'LHR',
        status: 'NORMAL',
        route: [
          { id: 'WP_E1', name: 'OSCAR', x: 360, y: 500, altitude: 30000 },
          { id: 'WP_E2', name: 'PAPA', x: 380, y: 260, altitude: 30000 },
          { id: 'WP_E3', name: 'QUEBEC', x: 400, y: 60, altitude: 30000 },
        ],
      }),
      createAircraft({
        id: 'AC106',
        callsign: 'AFR 088',
        model: 'A350-900',
        x: 650,
        y: 750,
        altitude: 35000,
        speed: 480,
        heading: 355,
        origin: 'HAV',
        destination: 'CDG',
        status: 'NORMAL',
        route: [
          { id: 'WP_F1', name: 'ROMEO', x: 640, y: 510, altitude: 35000 },
          { id: 'WP_F2', name: 'SIERRA', x: 620, y: 270, altitude: 35000 },
          { id: 'WP_F3', name: 'TANGO', x: 600, y: 60, altitude: 35000 },
        ],
      }),
      createAircraft({
        id: 'AC107',
        callsign: 'ANA 008',
        model: 'B777-200',
        x: 120,
        y: 120,
        altitude: 37000,
        speed: 500,
        heading: 125,
        origin: 'NRT',
        destination: 'JFK',
        status: 'NORMAL',
        route: [
          { id: 'WP_G1', name: 'UNIFORM', x: 380, y: 300, altitude: 37000 },
          { id: 'WP_G2', name: 'VICTOR', x: 640, y: 480, altitude: 37000 },
          { id: 'WP_G3', name: 'WHISKEY', x: 880, y: 660, altitude: 37000 },
        ],
      }),
      createAircraft({
        id: 'AC108',
        callsign: 'KLM 642',
        model: 'B787-9',
        x: 860,
        y: 120,
        altitude: 33000,
        speed: 470,
        heading: 235,
        origin: 'AMS',
        destination: 'DFW',
        status: 'NORMAL',
        route: [
          { id: 'WP_H1', name: 'XRAY', x: 620, y: 300, altitude: 33000 },
          { id: 'WP_H2', name: 'YANKEE', x: 360, y: 480, altitude: 33000 },
          { id: 'WP_H3', name: 'ZULU', x: 120, y: 660, altitude: 33000 },
        ],
      }),
    ],
    weatherZones: [
      createWeatherZone({
        id: 'WZ_MID_RAIN',
        name: 'Regional Rain Corridor',
        type: 'RAIN',
        severity: 'MODERATE',
        center: { x: 500, y: 380 },
        radius: 80,
        windSpeed: 42,
        windHeading: 180,
        visibility: 4.0,
        minAltitudeFt: 0,
        maxAltitudeFt: 35000,
        isActive: true,
        description: 'Moderate precipitation band along airway cross-points',
      }),
    ],
    restrictedZones: [],
  },

  // Phase 5: Scenario 3 - Dynamic Storm Reroute & MOA Hazard Matrix (8 Aircraft)
  scenario_phase5_storm_reroute: {
    id: 'scenario_phase5_storm_reroute',
    name: 'Phase 5: Storm Reroute & Restricted MOA Matrix',
    tagline: '8 Commercial Aircraft Navigating Dual Storm Fronts and Active Military Airspace',
    description:
      'Eight aircraft navigating through challenging environmental hazards including dual convective storm systems and an active military restricted zone with intelligent tactical vectoring.',
    aircraft: [
      createAircraft({
        id: 'AC201',
        callsign: 'SKY 303',
        model: 'B787-9',
        x: 80,
        y: 280,
        altitude: 33000,
        speed: 490,
        heading: 90,
        origin: 'SFO',
        destination: 'BOS',
        status: 'NORMAL',
        route: [
          { id: 'WP_S1', name: 'WAYPT-A', x: 260, y: 280, altitude: 33000 },
          { id: 'WP_S2', name: 'WAYPT-B', x: 500, y: 180, altitude: 33000 },
          { id: 'WP_S3', name: 'WAYPT-C', x: 820, y: 280, altitude: 33000 },
        ],
      }),
      createAircraft({
        id: 'AC202',
        callsign: 'AAL 904',
        model: 'A321neo',
        x: 100,
        y: 480,
        altitude: 31000,
        speed: 460,
        heading: 90,
        origin: 'LAX',
        destination: 'JFK',
        status: 'NORMAL',
        route: [
          { id: 'WP_S4', name: 'WAYPT-D', x: 300, y: 480, altitude: 31000 },
          { id: 'WP_S5', name: 'WAYPT-E', x: 540, y: 600, altitude: 31000 },
          { id: 'WP_S6', name: 'WAYPT-F', x: 860, y: 480, altitude: 31000 },
        ],
      }),
      createAircraft({
        id: 'AC203',
        callsign: 'DLH 512',
        model: 'A350-900',
        x: 880,
        y: 300,
        altitude: 35000,
        speed: 510,
        heading: 270,
        origin: 'MUC',
        destination: 'ORD',
        status: 'NORMAL',
        route: [
          { id: 'WP_S7', name: 'WAYPT-G', x: 680, y: 300, altitude: 35000 },
          { id: 'WP_S8', name: 'WAYPT-H', x: 460, y: 190, altitude: 35000 },
          { id: 'WP_S9', name: 'WAYPT-I', x: 120, y: 300, altitude: 35000 },
        ],
      }),
      createAircraft({
        id: 'AC204',
        callsign: 'BAW 442',
        model: 'B777-300',
        x: 880,
        y: 500,
        altitude: 37000,
        speed: 480,
        heading: 270,
        origin: 'LHR',
        destination: 'IAH',
        status: 'NORMAL',
        route: [
          { id: 'WP_S10', name: 'WAYPT-J', x: 650, y: 500, altitude: 37000 },
          { id: 'WP_S11', name: 'WAYPT-K', x: 420, y: 610, altitude: 37000 },
          { id: 'WP_S12', name: 'WAYPT-L', x: 100, y: 500, altitude: 37000 },
        ],
      }),
      createAircraft({
        id: 'AC205',
        callsign: 'UAL 318',
        model: 'B737-MAX8',
        x: 300,
        y: 720,
        altitude: 28000,
        speed: 430,
        heading: 10,
        origin: 'MIA',
        destination: 'YYZ',
        status: 'NORMAL',
        route: [
          { id: 'WP_S13', name: 'WAYPT-M', x: 310, y: 510, altitude: 28000 },
          { id: 'WP_S14', name: 'WAYPT-N', x: 320, y: 280, altitude: 28000 },
          { id: 'WP_S15', name: 'WAYPT-P', x: 330, y: 80, altitude: 28000 },
        ],
      }),
      createAircraft({
        id: 'AC206',
        callsign: 'SIA 026',
        model: 'A380-800',
        x: 700,
        y: 720,
        altitude: 39000,
        speed: 520,
        heading: 350,
        origin: 'SIN',
        destination: 'JFK',
        status: 'NORMAL',
        route: [
          { id: 'WP_S16', name: 'WAYPT-Q', x: 690, y: 510, altitude: 39000 },
          { id: 'WP_S17', name: 'WAYPT-R', x: 680, y: 280, altitude: 39000 },
          { id: 'WP_S18', name: 'WAYPT-S', x: 670, y: 80, altitude: 39000 },
        ],
      }),
      createAircraft({
        id: 'AC207',
        callsign: 'AFR 442',
        model: 'A330-300',
        x: 180,
        y: 100,
        altitude: 36000,
        speed: 485,
        heading: 145,
        origin: 'CDG',
        destination: 'MCO',
        status: 'NORMAL',
        route: [
          { id: 'WP_S19', name: 'WAYPT-T', x: 380, y: 260, altitude: 36000 },
          { id: 'WP_S20', name: 'WAYPT-U', x: 580, y: 440, altitude: 36000 },
          { id: 'WP_S21', name: 'WAYPT-V', x: 800, y: 640, altitude: 36000 },
        ],
      }),
      createAircraft({
        id: 'AC208',
        callsign: 'JAL 062',
        model: 'B787-8',
        x: 820,
        y: 100,
        altitude: 34000,
        speed: 475,
        heading: 215,
        origin: 'HND',
        destination: 'DFW',
        status: 'NORMAL',
        route: [
          { id: 'WP_S22', name: 'WAYPT-W', x: 620, y: 260, altitude: 34000 },
          { id: 'WP_S23', name: 'WAYPT-X', x: 420, y: 440, altitude: 34000 },
          { id: 'WP_S24', name: 'WAYPT-Y', x: 200, y: 640, altitude: 34000 },
        ],
      }),
    ],
    weatherZones: [
      createWeatherZone({
        id: 'WZ_STORM_NORTH',
        name: 'Northern Supercell Bravo',
        type: 'THUNDERSTORM',
        severity: 'CRITICAL',
        center: { x: 500, y: 280 },
        radius: 85,
        windSpeed: 75,
        windHeading: 240,
        visibility: 0.8,
        minAltitudeFt: 0,
        maxAltitudeFt: 45000,
        isActive: true,
        description: 'Severe convective squall line across northern airway',
      }),
      createWeatherZone({
        id: 'WZ_STORM_SOUTH',
        name: 'Southern Squall Line Charlie',
        type: 'THUNDERSTORM',
        severity: 'HIGH',
        center: { x: 500, y: 520 },
        radius: 80,
        windSpeed: 60,
        windHeading: 190,
        visibility: 1.2,
        minAltitudeFt: 0,
        maxAltitudeFt: 40000,
        isActive: true,
        description: 'Active storm band obstructing southern transit corridor',
      }),
    ],
    restrictedZones: [
      {
        id: 'RZ_MOA_CENTRAL',
        name: 'Restricted Airspace R-4401',
        center: { x: 500, y: 400 },
        radius: 50,
        minAltitudeFt: 0,
        maxAltitudeFt: 50000,
        status: 'RESTRICTED',
        description: 'Active Military Intercept Training Range',
      },
    ],
  },
};
